# .github/workflows/download-vk.zip1.yml
name: Download .zip1 from VK (scrape)

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'Search keyword for posts'
        required: true
        default: ''

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Download .zip1 from VK
        id: download
        run: |
          python scripts/vk_scrape_download.py \
            --keyword "${{ github.event.inputs.keyword }}" \
            --owner "doujinmusic" \
            --out-dir downloaded
          ls downloaded/*.zip1 > /dev/null 2>&1
          echo "FOUND=$?" >> $GITHUB_ENV

      - name: Commit and push if files exist
        if: env.FOUND == '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add downloaded/*.zip1
          git commit -m "Add downloaded .zip1 files from VK"
          git push

      - name: No files found
        if: env.FOUND != '0'
        run: |
          echo "No .zip1 files found, skipping commit." 
